services:
    Amqp/Connection:
        factory:
            class: Amqp/ConnectionFactory
            method: 'create'
        arguments: ['%amqplib', '%env(RABBIT_DSN)%']
    Image/SimpleResizer:
        class: Image/SimpleResizer